### ISSUE TITLE
Incorrect highlighting of /$ inside triple-quoted multiline strings

### ISSUE THREAD

**Issue by sah** [Groovy-Emacs-Modes/groovy-emacs-modes#95]
"""
    /$
    """
    
    def foo() {  // this line is still highlighted as part of a string!

**Comment by Wilfred** [comment]
I can no longer reproduce this. Probably fixed by #98.

**Comment by rmm5t** [comment]
I'm still experiencing this issue. Can we please re-open this?

<img width="518" alt="jenkinsfile account-service 2018-04-08 17-01-26" src="https://user-images.githubusercontent.com/740/38473520-7cbe275c-3b4e-11e8-9078-8d09dc0e9aa1.png">

**Comment by Wilfred** [comment]
Ha, string highlighting is continuing challenge in this code :)
